### ISSUE TITLE
Add coverage analysis, Coveralls

### ISSUE THREAD

**Issue by aantron** [aantron/repromise#43]
[Bisect_ppx](https://github.com/aantron/bisect_ppx#readme) now supports both [native](https://github.com/aantron/bisect_ppx#Dune) and [BuckleScript](https://github.com/aantron/bisect_ppx#BuckleScript) coverage, so use it.

- [x] `make coverage` for local reports.
- [x] Submit to Travis, from two build rows (opam and npm).
- [x] Add coverage badge.
- [x] JS: fix `[@coverage exclude(file)]` upstream, and adapt to that.
- [ ] JS: fix `ppx-flags` being global, and adapt to that. aantron/bisect_ppx#221
- [ ] JS: fix that instrumentation should automatically only be enabled in dev builds, perhaps also when some flag is specified. aantron/bisect_ppx#221
- [ ] Native: wait for ocaml/dune#57, and adapt to that.
- [ ] JS, esy: relax 4.06 OCaml constraint for development. See https://github.com/aantron/bisect_ppx/issues/220.

**Comment by aantron** [comment]
On BuckleScript, we need to be able to exclude the test suite.

1. With `bs-platform > 6.0.3`, it will be possible to pass `--exclude-file` to Bisect_ppx, which can exclude all test files in one swoop. This is not ideal, as `--exclude-file` is for working around build system issues.
2. The right way to fix this is to adjust the `bsconfig.json` schema to be able to specify `ppx-flags` per directory, so we can specify them in `src/` only.
3. For now, we are using `[@@@coverage exclude file]` in each test file, which is annoying, but less annoying than installing `bs-platform` `master` as in (1).

**Comment by aantron** [comment]
Development with BuckleScript or esy is now locked to OCaml 4.06 and BuckleScript 6.x.x, until https://github.com/aantron/bisect_ppx/issues/220 is resolved.

**Comment by aantron** [comment]
Blocked on better integration of Bisect_ppx with BuckleScript (https://github.com/BuckleScript/bucklescript/issues/3761).

I disabled coverage on JS for now, because it's too annoying not to be able to use Bisect_ppx as a dev PPX. Coverage is still working on native, because the native library is not published to any package managers.
